### ISSUE TITLE
No Type DockGroup

### ISSUE THREAD

**Issue by arunpkio** [HamedMasafi/qmldock#1]
When I try to compile and run the example I get this error

`qrc:/main.qml:18:9: DockGroup is not a type`

I have checked the source code and couldn't find any class related to **_DockGroup_**

**Comment by HamedMasafi** [comment]
Hi @arunpkqt 
There are some new changes. Please switch to _dev_ branch. The changes will be moved into the _main_ branch asap.

BR

**Comment by arunpkio** [comment]
@HamedMasafi  I have already tried `dev` branch, but the issue still persists. Haven't seen the code for `DockGroup`

**Comment by HamedMasafi** [comment]
Ok, let me check it. I'll be pushed new commit within next 24hrs

**Comment by HamedMasafi** [comment]
Fixed: Checkout the _dev_ branch
